version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: nom035-mysql
    environment:
      MYSQL_DATABASE: nom035
      MYSQL_ROOT_PASSWORD: your_mysql_password
      MYSQL_USER: nom035user
      MYSQL_PASSWORD: nom035pass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nom035-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/nom035?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: your_mysql_password
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    restart: on-failure

volumes:
  db_data: