INSERT INTO question (id,survey_id,`text`,response_type,sort_order,risk_factor,category,guide_type,survey_title,metadata) VALUES
	 (1,1,'¿El espacio donde trabaja le permite realizar sus tareas de forma higiénica y segura?','likert',1,'Condiciones físicas','Ambiente',NULL,'Guía I - Condiciones de Trabajo',NULL),
	 (2,1,'¿Su trabajo le exige hacer mucho esfuerzo físico?','likert',2,'Esfuerzo físico','Ambiente',NULL,'Guía I - Condiciones de Trabajo',NULL),
	 (3,1,'¿Le preocupa sufrir un accidente en su trabajo como consecuencia del espacio donde lo realiza?','likert',3,'Seguridad','Ambiente',NULL,'Guía I - Condiciones de Trabajo',NULL),
	 (4,1,'¿Considera que en su trabajo se aplican las normas de seguridad y salud laboral?','likert',4,'Normas de seguridad','Ambiente',NULL,'Guía I - Condiciones de Trabajo',NULL),
	 (5,1,'¿Debido al alto volumen de trabajo tiene que disponer de horas adicionales a su turno habitual?','likert',5,'Sobrecarga','Carga',NULL,'Guía I - Condiciones de Trabajo',NULL),
	 (6,1,'¿Debido al alto volumen de trabajo no puede disponer de una pausa durante su jornada habitual?','likert',6,'Pausas','Carga',NULL,'Guía I - Condiciones de Trabajo',NULL),
	 (7,1,'¿Cree que es necesario llevar un ritmo de trabajo mas acelerado para cumplir con sus actividades cotidianas?','likert',7,'Ritmo','Carga',NULL,'Guía I - Condiciones de Trabajo',NULL),
	 (8,1,'¿Su trabajo le exige que esta muy concentrado en sus labores?','likert',8,'Concentración','Carga',NULL,'Guía I - Condiciones de Trabajo',NULL),
	 (9,1,'¿Su trabajo requiere que memorice una gran cantidad de información?','likert',9,'Memoria','Carga',NULL,'Guía I - Condiciones de Trabajo',NULL),
	 (10,1,'¿En su trabajo tiene que tomar decisiones complicadas de forma rápida?','likert',10,'Decisiones','Carga',NULL,'Guía I - Condiciones de Trabajo',NULL);
INSERT INTO question (id,survey_id,`text`,response_type,sort_order,risk_factor,category,guide_type,survey_title,metadata) VALUES
	 (11,1,'¿Su trabajo le exige que atienda varios asuntos al mismo tiempo?','likert',11,'Multitarea','Carga',NULL,'Guía I - Condiciones de Trabajo',NULL),
	 (12,1,'¿En su trabajo usted es responsable de objetos de un alto valor monetario?','likert',12,'Responsabilidad económica','Carga',NULL,'Guía I - Condiciones de Trabajo',NULL),
	 (13,1,'¿Es responsable ante sus superiores de los resultados que obtenga todo su equipo o área de trabajo?','likert',13,'Responsabilidad grupal','Carga',NULL,'Guía I - Condiciones de Trabajo',NULL),
	 (14,1,'¿Considera que dentro de sus actividades diarias realiza alguna que sea fuera de su área de trabajo?','likert',14,'Actividades ajenas','Control',NULL,'Guía II - Factores de Riesgo Psicosocial',NULL),
	 (15,1,'¿Recibe ordenes contradictorias en su trabajo?','likert',15,'Órdenes contradictorias','Control',NULL,'Guía II - Factores de Riesgo Psicosocial',NULL),
	 (16,1,'¿Considera que realiza acciones innecesarias en el desarrollo de su trabajo?','likert',16,'Acciones innecesarias','Control',NULL,'Guía II - Factores de Riesgo Psicosocial',NULL),
	 (17,1,'¿Trabaja horas extraordinarias mas de tres veces por semana?','likert',17,'Horas extra','Jornada',NULL,'Guía II - Factores de Riesgo Psicosocial',NULL),
	 (18,1,'¿Su trabajo le exige laborar en días de descanso, festivos o fines de semana?','likert',18,'Días festivos','Jornada',NULL,'Guía II - Factores de Riesgo Psicosocial',NULL),
	 (19,1,'¿Considera que el tiempo de trabajo es excesivo y no le permite desarrollar su vida personal?','likert',19,'Equilibrio vida-trabajo','Jornada',NULL,'Guía II - Factores de Riesgo Psicosocial',NULL),
	 (20,1,'¿Atiende usted asuntos laborales cuando se encuentra en casa?','likert',20,'Trabajo en casa','Jornada',NULL,'Guía II - Factores de Riesgo Psicosocial',NULL);
INSERT INTO question (id,survey_id,`text`,response_type,sort_order,risk_factor,category,guide_type,survey_title,metadata) VALUES
	 (21,1,'¿Piensa en actividades personales cuando esta en el trabajo?','likert',21,'Distracción personal','Jornada',NULL,'Guía II - Factores de Riesgo Psicosocial',NULL),
	 (22,1,'¿Cree usted que sus responsabilidades familiares o personales afectan su trabajo?','likert',22,'Interferencia familiar','Jornada',NULL,'Guía II - Factores de Riesgo Psicosocial',NULL),
	 (23,1,'¿Su trabajo le permite que desarrolle nuevas habilidades?','likert',23,'Desarrollo de habilidades','Desarrollo',NULL,'Guía II - Factores de Riesgo Psicosocial',NULL),
	 (24,1,'¿En su trabajo puede aspirar a un mejor puesto?','likert',24,'Promoción','Desarrollo',NULL,'Guía II - Factores de Riesgo Psicosocial',NULL),
	 (25,1,'¿Durante su jornada de trabajo puede tomar pausas cuando lo necesite?','likert',25,'Pausas necesarias','Autonomía',NULL,'Guía II - Factores de Riesgo Psicosocial',NULL),
	 (26,1,'¿Puede decidir que trabajo realiza y que trabajo no durante su jornada?','likert',26,'Decisión de tareas','Autonomía',NULL,'Guía II - Factores de Riesgo Psicosocial',NULL),
	 (27,1,'¿Puede manejar la velocidad a la cual realiza su trabajo?','likert',27,'Velocidad de trabajo','Autonomía',NULL,'Guía II - Factores de Riesgo Psicosocial',NULL),
	 (28,1,'¿Puede decidir el orden en el cual realizar sus tareas cotidianas?','likert',28,'Orden de tareas','Autonomía',NULL,'Guía II - Factores de Riesgo Psicosocial',NULL),
	 (29,1,'¿Los cambios en el trabajo dificulta sus labores cotidianas?','likert',29,'Cambios laborales','Cambio',NULL,'Guía II - Factores de Riesgo Psicosocial',NULL),
	 (30,1,'¿Con frecuencia se presentan cambios repentinos los cuales afectan en la realización de sus actividades?','likert',30,'Cambios repentinos','Cambio',NULL,'Guía II - Factores de Riesgo Psicosocial',NULL);
INSERT INTO question (id,survey_id,`text`,response_type,sort_order,risk_factor,category,guide_type,survey_title,metadata) VALUES
	 (31,1,'¿Cuándo se presenta oportunidad de cambio en el trabajo, toman en cuenta sus ideas/aportaciones?','likert',31,'Participación en cambios','Participación',NULL,'Guía II - Factores de Riesgo Psicosocial',NULL),
	 (32,1,'¿Le informan con claridad cuales son sus funciones?','likert',32,'Claridad de funciones','Funciones',NULL,'Guía III - Entorno Organizacional',NULL),
	 (33,1,'¿Se le explica con claridad los resultados que debe obtener en su trabajo?','likert',33,'Claridad de resultados','Funciones',NULL,'Guía III - Entorno Organizacional',NULL),
	 (34,1,'¿Se le explica con claridad el objetivo de su trabajo?','likert',34,'Claridad de objetivos','Funciones',NULL,'Guía III - Entorno Organizacional',NULL),
	 (35,1,'¿Le indican a quien debe dirigirse para resolver sus problemas o asuntos de trabajo?','likert',35,'Jerarquía clara','Funciones',NULL,'Guía III - Entorno Organizacional',NULL),
	 (36,1,'¿Le permiten asistir a capacitaciones relacionadas con su trabajo?','likert',36,'Acceso a capacitación','Capacitación',NULL,'Guía III - Entorno Organizacional',NULL),
	 (37,1,'¿Recibe capacitación útil para hacer bien su trabajo?','likert',37,'Utilidad de capacitación','Capacitación',NULL,'Guía III - Entorno Organizacional',NULL),
	 (38,1,'¿Su jefe le ayuda a organizar mejor su trabajo?','likert',38,'Organización del jefe','Liderazgo',NULL,'Guía III - Entorno Organizacional',NULL),
	 (39,1,'¿Su jefe tiene en cuenta sus puntos de vista y opiniones?','likert',39,'Consideración del jefe','Liderazgo',NULL,'Guía III - Entorno Organizacional',NULL),
	 (40,1,'¿Su jefe le comunica a tiempo la información relacionada con su trabajo?','likert',40,'Comunicación del jefe','Liderazgo',NULL,'Guía III - Entorno Organizacional',NULL);
INSERT INTO question (id,survey_id,`text`,response_type,sort_order,risk_factor,category,guide_type,survey_title,metadata) VALUES
	 (41,1,'¿Su jefe le da orientación suficiente para realizar su trabajo adecuadamente?','likert',41,'Orientación del jefe','Liderazgo',NULL,'Guía III - Entorno Organizacional',NULL),
	 (42,1,'¿Su jefe le ayuda a solucionar los problemas que se le presentan en el trabajo?','likert',42,'Apoyo del jefe','Liderazgo',NULL,'Guía III - Entorno Organizacional',NULL),
	 (43,1,'¿Confía en sus compañeros de trabajo?','likert',43,'Confianza en compañeros','Relaciones',NULL,'Guía III - Entorno Organizacional',NULL),
	 (44,1,'¿Entre compañeros logran solucionar los problemas de trabajo de una forma respetuosa?','likert',44,'Solución respetuosa','Relaciones',NULL,'Guía III - Entorno Organizacional',NULL),
	 (45,1,'¿En su trabajo le hacen sentir parte del grupo?','likert',45,'Pertenencia al grupo','Relaciones',NULL,'Guía III - Entorno Organizacional',NULL),
	 (46,1,'¿Recibe ayuda de sus compañeros cuando tiene que realizar un trabajo en equipo?','likert',46,'Ayuda en equipo','Relaciones',NULL,'Guía III - Entorno Organizacional',NULL),
	 (47,1,'¿Sus compañeros de trabajo le ayudan cuando tiene dificultades?','likert',47,'Ayuda en dificultades','Relaciones',NULL,'Guía III - Entorno Organizacional',NULL),
	 (48,1,'¿Le informan sobre lo que hace bien o mal en el trabajo?','likert',48,'Retroalimentación','Desempeño',NULL,'Encuesta de Satisfacción',NULL),
	 (49,1,'¿La forma como le evalúan en su centro de trabajo le ayuda a mejorar su desempeño?','likert',49,'Evaluación constructiva','Desempeño',NULL,'Encuesta de Satisfacción',NULL),
	 (50,1,'¿En su centro de trabajo le pagan a tiempo su salario?','likert',50,'Pago puntual','Reconocimiento',NULL,'Encuesta de Satisfacción',NULL);
INSERT INTO question (id,survey_id,`text`,response_type,sort_order,risk_factor,category,guide_type,survey_title,metadata) VALUES
	 (51,1,'¿El pago que recibe es el que merece por el trabajo realizado?','likert',51,'Pago justo','Reconocimiento',NULL,'Encuesta de Satisfacción',NULL),
	 (52,1,'¿Al obtener los resultados esperados de su trabajo le reconocen o recompensan?','likert',52,'Recompensas','Reconocimiento',NULL,'Encuesta de Satisfacción',NULL),
	 (53,1,'¿Quién realiza bien el trabajo puede crecer laboralmente dentro de su centro de trabajo?','likert',53,'Crecimiento laboral','Reconocimiento',NULL,'Encuesta de Satisfacción',NULL),
	 (54,1,'¿Considera que su trabajo es estable?','likert',54,'Estabilidad laboral','Pertenencia',NULL,'Encuesta de Satisfacción',NULL),
	 (55,1,'¿Existe continua rotación de personal en su trabajo?','likert',55,'Rotación de personal','Pertenencia',NULL,'Encuesta de Satisfacción',NULL),
	 (56,1,'¿Siente orgullo de laborar en este centro de trabajo?','likert',56,'Orgullo laboral','Pertenencia',NULL,'Encuesta de Satisfacción',NULL),
	 (57,1,'¿Se siente comprometido con su trabajo?','likert',57,'Compromiso laboral','Pertenencia',NULL,'Encuesta de Satisfacción',NULL),
	 (58,1,'¿En su trabajo puede expresarse libremente sin interrupciones?','likert',58,'Libertad de expresión','Violencia',NULL,'Encuesta de Comunicación Interna',NULL),
	 (59,1,'¿Recibe constantemente críticas sobre su trabajo o sobre su persona?','likert',59,'Críticas constantes','Violencia',NULL,'Encuesta de Comunicación Interna',NULL),
	 (60,1,'¿Recibe burlas, calumnias, difamaciones o humillaciones en su trabajo?','likert',60,'Burlas y humillaciones','Violencia',NULL,'Encuesta de Comunicación Interna',NULL);
INSERT INTO question (id,survey_id,`text`,response_type,sort_order,risk_factor,category,guide_type,survey_title,metadata) VALUES
	 (61,1,'¿Ignoran su presencia o es excluido de las reuniones de trabajo y toma de decisiones?','likert',61,'Exclusión social','Violencia',NULL,'Encuesta de Comunicación Interna',NULL),
	 (62,1,'¿Se manipulan las situaciones de trabajo para hacerle parecer un mal trabajador?','likert',62,'Manipulación laboral','Violencia',NULL,'Encuesta de Comunicación Interna',NULL),
	 (63,1,'¿Sus éxitos laborales son ignorados y atribuidos a otros trabajadores?','likert',63,'Robo de méritos','Violencia',NULL,'Encuesta de Comunicación Interna',NULL),
	 (64,1,'¿Sus oportunidades de tener un ascenso o mejora laboral son bloqueadas o impedidas?','likert',64,'Bloqueo de ascensos','Violencia',NULL,'Encuesta de Comunicación Interna',NULL),
	 (65,1,'¿Ha presenciado actos de violencia en su centro de trabajo?','likert',65,'Violencia presenciada','Violencia',NULL,'Encuesta de Comunicación Interna',NULL),
	 (66,1,'¿Atiende a clientes o usuarios muy enojados?','likert',66,'Clientes enojados','Actividad',NULL,'Encuesta de Comunicación Interna',NULL),
	 (67,1,'¿Su trabajo le exige atender a personas muy necesitadas de ayuda o enfermas?','likert',67,'Personas necesitadas','Actividad',NULL,'Encuesta de Comunicación Interna',NULL),
	 (68,1,'¿Para hacer su trabajo debe demostrar sentimientos distintos a los suyos?','likert',68,'Trabajo emocional','Actividad',NULL,'Encuesta de Comunicación Interna',NULL),
	 (69,1,'¿Su trabajo le exige atender situaciones de violencia?','likert',69,'Situaciones de violencia','Actividad',NULL,'Encuesta de Comunicación Interna',NULL),
	 (70,1,'¿Sus subalternos comunican tarde los asuntos de trabajo?','likert',70,'Comunicación tardía subalternos','Liderazgo trabajadores',NULL,'Encuesta de Comunicación Interna',NULL);
INSERT INTO question (id,survey_id,`text`,response_type,sort_order,risk_factor,category,guide_type,survey_title,metadata) VALUES
	 (71,1,'¿Sus subalternos dificultan el logro de los objetivos de trabajo?','likert',71,'Obstaculización objetivos','Liderazgo trabajadores',NULL,'Encuesta de Comunicación Interna',NULL),
	 (72,1,'¿Sus subalternos cooperan poco en las actividades cotidianas cuando se les requiere?','likert',72,'Falta de cooperación','Liderazgo trabajadores',NULL,'Encuesta de Comunicación Interna',NULL),
	 (73,1,'¿Sus subalternos ignoran las sugerencias que se le hacen para mejorar su trabajo?','likert',73,'Ignorar sugerencias','Liderazgo trabajadores',NULL,'Encuesta de Comunicación Interna',NULL),
	 (74,2,'Nombre','text',1,NULL,'Datos generales','Personalizado','Encuesta Médica Leben',NULL),
	 (75,2,'Fecha de Nacimiento','date',2,NULL,'Datos generales','Personalizado','Encuesta Médica Leben',NULL),
	 (76,2,'Departamento en el que labora','text',3,NULL,'Datos generales','Personalizado','Encuesta Médica Leben',NULL),
	 (77,2,'Puesto','text',4,NULL,'Datos generales','Personalizado','Encuesta Médica Leben',NULL),
	 (78,2,'Estado Civil','single_choice',5,NULL,'Datos generales','Personalizado','Encuesta Médica Leben',NULL),
	 (79,2,'Sexo','single_choice',6,NULL,'Datos generales','Personalizado','Encuesta Médica Leben',NULL),
	 (80,2,'Estudios realizados','single_choice',7,NULL,'Datos generales','Personalizado','Encuesta Médica Leben',NULL);
INSERT INTO question (id,survey_id,`text`,response_type,sort_order,risk_factor,category,guide_type,survey_title,metadata) VALUES
	 (81,2,'¿Cuál es su categoría dentro de la empresa?','single_choice',8,NULL,'Datos generales','Personalizado','Encuesta Médica Leben',NULL),
	 (82,2,'¿Antigüedad en el puesto?','single_choice',9,NULL,'Datos generales','Personalizado','Encuesta Médica Leben',NULL),
	 (83,2,'¿Cuánto tiempo hace que labora en el mismo lugar de trabajo (edificio, local o planta)?','single_choice',10,NULL,'Datos generales','Personalizado','Encuesta Médica Leben',NULL),
	 (84,2,'Seleccione los días de la semana en trabaja usted','single_choice',11,NULL,'Datos generales','Personalizado','Encuesta Médica Leben',NULL),
	 (85,2,'¿Cuántas horas trabaja al día?','single_choice',12,NULL,'Datos generales','Personalizado','Encuesta Médica Leben',NULL),
	 (86,2,'¿Qué medio de transporte utiliza para llegar a su trabajo?','single_choice',13,NULL,'Datos generales','Personalizado','Encuesta Médica Leben',NULL),
	 (87,2,'En caso de tener vehículo propio, ¿Cuántos tiene?','single_choice',14,NULL,'Datos generales','Personalizado','Encuesta Médica Leben',NULL),
	 (88,2,'En caso de contar con vehículo propio ¿Cuánto gasta en gasolina a la semana?','single_choice',15,NULL,'Datos generales','Personalizado','Encuesta Médica Leben',NULL),
	 (89,2,'¿Cuánto tiempo hace de traslado a su trabajo?','single_choice',16,NULL,'Datos generales','Personalizado','Encuesta Médica Leben',NULL),
	 (90,2,'En caso de usar transporte publico (taxi, Uber, camión) para llegar a su centro de trabajo, ¿Cuánto gasta diariamente?','single_choice',17,NULL,'Datos generales','Personalizado','Encuesta Médica Leben',NULL);
INSERT INTO question (id,survey_id,`text`,response_type,sort_order,risk_factor,category,guide_type,survey_title,metadata) VALUES
	 (91,2,'¿La casa o departamento en el que habita es?','single_choice',18,NULL,'Datos generales','Personalizado','Encuesta Médica Leben',NULL),
	 (92,2,'¿Cuántas veces a la semana consume los siguientes alimentos?','matrix',19,NULL,'Datos generales','Personalizado','Encuesta Médica Leben','{"rows": ["Frutas y verduras", "Carnes Rojas y Lácteos", "Cereales (Tortilla Arroz Quinoa Papa)", "Semillas (Cacahuate Almendras Pistache)"], "columns": ["No consumo", "menos de 1 vez a la semana", "1 a 2 veces a la semana", "3 a 4 veces a la semana", "5 o mas veces a la semana"], "selection": "checkbox"}'),
	 (93,2,'¿Tiene la posibilidad de acceder a una alimentación sana, variada e higiénica?','single_choice',20,NULL,'Datos generales','Personalizado','Encuesta Médica Leben',NULL),
	 (94,2,'¿Cuántas veces sale de vacaciones al año?','single_choice',21,NULL,'Datos generales','Personalizado','Encuesta Médica Leben',NULL),
	 (95,2,'En caso de tener hijos, la Educación que reciben es','single_choice',22,NULL,'Datos generales','Personalizado','Encuesta Médica Leben',NULL),
	 (96,2,'¿En qué posición realizas la mayoría de tus actividades laborales?','single_choice',23,NULL,'Ambiente laboral','Personalizado','Encuesta Médica Leben',NULL),
	 (97,2,'¿Su lugar de trabajo cuenta con ventilación?','single_choice',24,NULL,'Ambiente laboral','Personalizado','Encuesta Médica Leben',NULL),
	 (98,2,'Seleccione el tipo de ventilación con la que cuenta su lugar de trabajo','single_choice',25,NULL,'Ambiente laboral','Personalizado','Encuesta Médica Leben',NULL),
	 (99,2,'La temperatura de su lugar de trabajo es','single_choice',26,NULL,'Ambiente laboral','Personalizado','Encuesta Médica Leben',NULL),
	 (100,2,'¿Qué le produce la temperatura de su lugar de trabajo?','single_choice',27,NULL,'Ambiente laboral','Personalizado','Encuesta Médica Leben',NULL);
INSERT INTO question (id,survey_id,`text`,response_type,sort_order,risk_factor,category,guide_type,survey_title,metadata) VALUES
	 (101,2,'En su lugar de trabajo se perciben olores de','single_choice',28,NULL,'Ambiente laboral','Personalizado','Encuesta Médica Leben','{"otherOption": true, "otherPrompts": ["Otros:"]}'),
	 (102,2,'¿Cómo es la iluminación en su lugar de trabajo?','single_choice',29,NULL,'Ambiente laboral','Personalizado','Encuesta Médica Leben',NULL),
	 (103,2,'De las siguientes opciones ¿Qué le incomoda en su lugar de trabajo?','multi_select',30,NULL,'Ambiente laboral','Personalizado','Encuesta Médica Leben','{"otherOption": true, "otherPrompts": ["Otros:"]}'),
	 (104,2,'¿En su lugar de trabajo existe ruido?','single_choice',31,NULL,'Ambiente laboral','Personalizado','Encuesta Médica Leben',NULL),
	 (105,2,'El nivel de ruido en su puesto de trabajo es','single_choice',32,NULL,'Ambiente laboral','Personalizado','Encuesta Médica Leben',NULL),
	 (106,2,'El ruido en su lugar de trabajo procede de','single_choice',33,NULL,'Ambiente laboral','Personalizado','Encuesta Médica Leben','{"otherOption": true, "otherPrompts": ["Otros:"]}'),
	 (107,2,'Aproximadamente ¿Cuánto tiempo está expuesto al ruido en su área de trabajo?','single_choice',34,NULL,'Ambiente laboral','Personalizado','Encuesta Médica Leben',NULL),
	 (108,2,'¿Conoce cuál es el nivel sonoro en decibeles en su área de trabajo?','single_choice',35,NULL,'Ambiente laboral','Personalizado','Encuesta Médica Leben',NULL),
	 (109,2,'¿Existen vibraciones producidas por herramientas manuales, máquinas, vehículos, etc. en su puesto de trabajo?','single_choice',36,NULL,'Ambiente laboral','Personalizado','Encuesta Médica Leben',NULL),
	 (110,2,'¿Estás expuesto a radiaciones ionizantes o no ionizantes en tu jornada laboral?','single_choice',37,NULL,'Ambiente laboral','Personalizado','Encuesta Médica Leben',NULL);
INSERT INTO question (id,survey_id,`text`,response_type,sort_order,risk_factor,category,guide_type,survey_title,metadata) VALUES
	 (111,2,'Indique el tipo de  radiación ionizante y no ionizante, al que está usted expuesto','multi_select',38,NULL,'Ambiente laboral','Personalizado','Encuesta Médica Leben',NULL),
	 (112,2,'¿En su área de trabajo existe algún tipo de radiación ionizante?','single_choice',39,NULL,'Ambiente laboral','Personalizado','Encuesta Médica Leben',NULL),
	 (113,2,'¿Cuenta usted con equipo de protección personal para radiación ionizante?','single_choice',40,NULL,'Ambiente laboral','Personalizado','Encuesta Médica Leben',NULL),
	 (114,2,'En caso de ser afirmativa la respuesta anterior, ¿Con qué tipo de equipo de protección personal cuenta?','single_choice',41,NULL,'Ambiente laboral','Personalizado','Encuesta Médica Leben',NULL),
	 (115,2,'¿Desarrolla usted trabajos en alturas mayores a 1.80 metros?','single_choice',42,NULL,'Ambiente laboral','Personalizado','Encuesta Médica Leben',NULL),
	 (116,2,'En caso de ser afirmativa la respuesta anterior, ¿Con que tipo de equipo de protección personal cuenta?','single_choice',43,NULL,'Ambiente laboral','Personalizado','Encuesta Médica Leben',NULL),
	 (117,2,'¿Qué riesgos asociados al trabajo en alturas conoce?','single_choice',44,NULL,'Ambiente laboral','Personalizado','Encuesta Médica Leben',NULL),
	 (118,2,'¿Desarrolla usted trabajos con soldadura?','single_choice',45,NULL,'Condiciones laborales','Personalizado','Encuesta Médica Leben',NULL),
	 (119,2,'¿Utiliza ropa adecuada y Equipo de protección especial para la soldadura?','single_choice',46,NULL,'Condiciones laborales','Personalizado','Encuesta Médica Leben',NULL),
	 (120,2,'Conoce los riesgos y medidas preventivas en los trabajos de soldaduras contaminantes, químicos en soldadura y tipo de contaminante químico que utiliza en su área laboral','single_choice',47,NULL,'Condiciones laborales','Personalizado','Encuesta Médica Leben',NULL);
INSERT INTO question (id,survey_id,`text`,response_type,sort_order,risk_factor,category,guide_type,survey_title,metadata) VALUES
	 (121,2,'Conoce los riesgos de soldaduras, caídas en distintos niveles, pisadas sobre objetos, cortes, proyección de fragmentos y contactos eléctricos?','single_choice',48,NULL,'Condiciones laborales','Personalizado','Encuesta Médica Leben',NULL),
	 (122,2,'¿Qué tipos de riesgos de trabajo en actividades de soldadura conoce?','single_choice',49,NULL,'Condiciones laborales','Personalizado','Encuesta Médica Leben',NULL),
	 (123,2,'¿Conoce las medidas de primeros auxilios básicos para quemaduras?','single_choice',50,NULL,'Condiciones laborales','Personalizado','Encuesta Médica Leben',NULL),
	 (124,2,'Su área de trabajo ¿Cuenta con botiquín de primeros auxilios?','single_choice',51,NULL,'Condiciones laborales','Personalizado','Encuesta Médica Leben',NULL),
	 (125,2,'Su área de trabajo ¿Cuenta con extintores?','single_choice',52,NULL,'Condiciones laborales','Personalizado','Encuesta Médica Leben',NULL),
	 (126,2,'Su área de trabajo ¿Cuenta con señaléticas de prevención de accidentes?','single_choice',53,NULL,'Condiciones laborales','Personalizado','Encuesta Médica Leben',NULL),
	 (127,2,'Independientemente de la labor que realice, su área de trabajo ¿Cuenta con Equipo de Protección Personal (EPP)?','single_choice',54,NULL,'Condiciones laborales','Personalizado','Encuesta Médica Leben',NULL),
	 (128,2,'En su área laboral ¿Cuenta con la capacitación suficiente para el manejo de herramientas y uso de máquinas según el tipo de área de producción y procesamiento?','single_choice',55,NULL,'Condiciones laborales','Personalizado','Encuesta Médica Leben',NULL),
	 (129,2,'En su trabajo ¿Se encuentra expuesto a temperaturas elevadas? (trabajos cerca de hornos, fogones, etc.)','single_choice',56,NULL,'Condiciones laborales','Personalizado','Encuesta Médica Leben',NULL),
	 (130,2,'En su trabajo ¿Se encuentra expuesto a temperaturas abatidas? (trabajos en cuartos fríos o de refrigeración)','single_choice',57,NULL,'Condiciones laborales','Personalizado','Encuesta Médica Leben',NULL);
INSERT INTO question (id,survey_id,`text`,response_type,sort_order,risk_factor,category,guide_type,survey_title,metadata) VALUES
	 (131,2,'En su puesto de trabajo, ¿Manipula sustancias o preparados nocivos o tóxicos?','single_choice',58,NULL,'Condiciones laborales','Personalizado','Encuesta Médica Leben',NULL),
	 (132,2,'En caso de ser afirmativa la respuesta anterior, indique que tipo de producto químico utiliza o está expuesto','single_choice',59,NULL,'Condiciones laborales','Personalizado','Encuesta Médica Leben',NULL),
	 (133,2,'Estas sustancias o preparados ¿Tienen alguna etiqueta o leyenda que informe de su peligrosidad?','single_choice',60,NULL,'Condiciones laborales','Personalizado','Encuesta Médica Leben',NULL),
	 (134,2,'En general, la información que contiene la etiqueta (símbolos, etc.) es','single_choice',61,NULL,'Condiciones laborales','Personalizado','Encuesta Médica Leben',NULL),
	 (135,2,'En su puesto de trabajo ¿Respira polvos, humos, aerosoles, gases o vapores nocivos o tóxicos? (excluido el humo del tabaco)','single_choice',62,NULL,'Condiciones laborales','Personalizado','Encuesta Médica Leben',NULL),
	 (136,2,'En su trabajo, ¿Maneja o tiene contacto directo con materiales que pueden ser infecciosos, tales como desechos, fluidos corporales, materiales de laboratorio, animales?','single_choice',63,NULL,'Condiciones laborales','Personalizado','Encuesta Médica Leben',NULL),
	 (137,2,'¿Conoce usted los posibles efectos perjudiciales para su salud de la manipulación y/o respiración de esas sustancias nocivas o tóxicas?','single_choice',64,NULL,'Condiciones laborales','Personalizado','Encuesta Médica Leben',NULL),
	 (138,2,'¿Le han informado en su empresa de las medidas a adoptar para prevenir estos posibles efectos perjudiciales?','single_choice',65,NULL,'Condiciones laborales','Personalizado','Encuesta Médica Leben',NULL),
	 (139,2,'En general, el nivel de atención que debe mantener para realizar su trabajo es','single_choice',66,NULL,'Condiciones laborales','Personalizado','Encuesta Médica Leben',NULL),
	 (140,2,'En los últimos 3 meses, la cantidad de trabajo que ha tenido generalmente es','single_choice',67,NULL,'Condiciones laborales','Personalizado','Encuesta Médica Leben',NULL);
INSERT INTO question (id,survey_id,`text`,response_type,sort_order,risk_factor,category,guide_type,survey_title,metadata) VALUES
	 (141,2,'El ritmo de trabajo está determinado por','single_choice',68,NULL,'Condiciones laborales','Personalizado','Encuesta Médica Leben',NULL),
	 (142,2,'El ritmo de trabajo es','single_choice',69,NULL,'Condiciones laborales','Personalizado','Encuesta Médica Leben',NULL),
	 (143,2,'Cuando en su puesto de trabajo se comete algún error, ¿Qué sucede?','single_choice',70,NULL,'Condiciones laborales','Personalizado','Encuesta Médica Leben',NULL),
	 (144,2,'Le parece adecuado su horario de trabajo?','single_choice',71,NULL,'Condiciones laborales','Personalizado','Encuesta Médica Leben',NULL),
	 (145,2,'¿Considera que tiene que realizar tareas que no le corresponden?','single_choice',72,NULL,'Condiciones laborales','Personalizado','Encuesta Médica Leben',NULL),
	 (146,2,'¿Hasta qué punto puede tomar decisiones en su trabajo?','single_choice',73,NULL,'Condiciones laborales','Personalizado','Encuesta Médica Leben',NULL),
	 (147,2,'¿Cómo considera que son las relaciones con las personas con las que debe trabajar?','matrix',74,NULL,'Condiciones laborales','Personalizado','Encuesta Médica Leben','{"rows": ["Jefes", "Compañeros", "Subordinados"], "columns": ["Buena", "Regular", "Mala"], "selection": "checkbox"}'),
	 (148,2,'¿Existe algún obstáculo que dificulte la comunicación con sus compañeros?','single_choice',75,NULL,'Condiciones laborales','Personalizado','Encuesta Médica Leben',NULL),
	 (149,2,'En caso de ser afirmativa la respuesta anterior, ¿Cuál de los siguientes aspectos dificulta esta comunicación? (Si es necesario marque mas de una respuesta)','multi_select',76,NULL,'Condiciones laborales','Personalizado','Encuesta Médica Leben',NULL),
	 (150,2,'¿Ha asistido a cursos de capacitación o formación complementaria para el desempeño de su trabajo?','single_choice',77,NULL,'Hábitos y salud','Personalizado','Encuesta Médica Leben',NULL);
INSERT INTO question (id,survey_id,`text`,response_type,sort_order,risk_factor,category,guide_type,survey_title,metadata) VALUES
	 (151,2,'En caso de ser afirmativa la respuesta anterior, a ¿Cuántos cursos ha asistido?','single_choice',78,NULL,'Hábitos y salud','Personalizado','Encuesta Médica Leben',NULL),
	 (152,2,'¿Le parece suficiente la formación que le ha proporcionado la empresa en la que actualmente labora, para el desempeño de su trabajo?','single_choice',79,NULL,'Hábitos y salud','Personalizado','Encuesta Médica Leben',NULL),
	 (153,2,'¿Conoce si hay algún procedimiento establecido para la promoción del personal?','single_choice',80,NULL,'Hábitos y salud','Personalizado','Encuesta Médica Leben',NULL),
	 (154,2,'¿Qué tipo de contrato de trabajo tiene celebrado con la empresa en la que actualmente labora?','single_choice',81,NULL,'Hábitos y salud','Personalizado','Encuesta Médica Leben',NULL),
	 (155,2,'¿Cómo cree que esta considerado su puesto de trabajo en la empresa?','single_choice',82,NULL,'Hábitos y salud','Personalizado','Encuesta Médica Leben',NULL),
	 (156,2,'¿Qué tipo de preparación necesita para desempeñar su puesto de trabajo?','single_choice',83,NULL,'Hábitos y salud','Personalizado','Encuesta Médica Leben',NULL),
	 (157,2,'Además de su formación académica, ¿Para desarrollar su trabajo se requiere de aptitudes?','single_choice',84,NULL,'Hábitos y salud','Personalizado','Encuesta Médica Leben',NULL),
	 (158,2,'Usted fuma o fumaba?','single_choice',85,NULL,'Hábitos y salud','Personalizado','Encuesta Médica Leben',NULL),
	 (159,2,'Si la respuesta anterior fue "Si" podría especificar la cantidad de cigarros al día y los años que lleva fumando o que fumo?','text',86,NULL,'Hábitos y salud','Personalizado','Encuesta Médica Leben','{"otherPrompts": ["Tu Respuesta:"]}'),
	 (160,2,'Si no es usted fumador, ¿Considera que el humo de tabaco de los demás perjudica su salud?','single_choice',87,NULL,'Hábitos y salud','Personalizado','Encuesta Médica Leben',NULL);
INSERT INTO question (id,survey_id,`text`,response_type,sort_order,risk_factor,category,guide_type,survey_title,metadata) VALUES
	 (161,2,'En caso de ser afirmativa la respuesta anterior, ¿Con qué frecuencia está expuesto al humo de tabaco?','single_choice',88,NULL,'Hábitos y salud','Personalizado','Encuesta Médica Leben',NULL),
	 (162,2,'Consume o consumía alcohol?','single_choice',89,NULL,'Hábitos y salud','Personalizado','Encuesta Médica Leben',NULL),
	 (163,2,'Si la respuesta anterior fue "Si" pudieras especificar el tipo de alcohol (cerveza, tequila, etc.), la cantidad de consumo por semana (latas, vasos, botella) y el número de años que has consumido alcohol?','text',90,NULL,'Hábitos y salud','Personalizado','Encuesta Médica Leben','{"otherPrompts": ["Tu Respuesta:"]}'),
	 (164,2,'Realiza actividad física?','single_choice',91,NULL,'Hábitos y salud','Personalizado','Encuesta Médica Leben',NULL),
	 (165,2,'Con que frecuencia realiza actividad física a la semana (Tomando en cuenta que mínimo son 30 min al día)','single_choice',92,NULL,'Hábitos y salud','Personalizado','Encuesta Médica Leben',NULL),
	 (166,2,'Seleccione si en su familia ha habido casos de','multi_select',93,NULL,'Hábitos y salud','Personalizado','Encuesta Médica Leben',NULL),
	 (167,2,'¿Tiene usted alguno de los siguientes padecimientos heredofamiliares o crónicos degenerativos?','single_choice',94,NULL,'Hábitos y salud','Personalizado','Encuesta Médica Leben',NULL),
	 (168,2,'Si la respuesta anterior fue "Otros" favor de especificar la enfermedad que padece','text',95,NULL,'Hábitos y salud','Personalizado','Encuesta Médica Leben','{"otherPrompts": ["Tu Respuesta:"]}'),
	 (169,2,'Si padece alguno o algunos de los padecimientos señalados en la pregunta anterior, ¿lleva algún tratamiento de control?','single_choice',96,NULL,'Hábitos y salud','Personalizado','Encuesta Médica Leben',NULL),
	 (170,2,'Favor de especificar el nombre del  medicamento (os) o suplementos que consume','text',97,NULL,'Hábitos y salud','Personalizado','Encuesta Médica Leben','{"otherPrompts": ["Tu Respuesta:"]}');
INSERT INTO question (id,survey_id,`text`,response_type,sort_order,risk_factor,category,guide_type,survey_title,metadata) VALUES
	 (171,2,'Alergias: Si o No y favor de especificar a que es alérgico:','text',98,NULL,'Hábitos y salud','Personalizado','Encuesta Médica Leben','{"otherPrompts": ["Favor de especificar a qué es alérgico:"]}'),
	 (172,2,'¿Alguna vez ha sufrido un accidente de trabajo?','single_choice',99,NULL,'Hábitos y salud','Personalizado','Encuesta Médica Leben',NULL),
	 (173,2,'En caso de ser afirmativa la respuesta anterior, mencione  ¿Cuál?','text',100,NULL,'Hábitos y salud','Personalizado','Encuesta Médica Leben','{"otherPrompts": ["Tu Respuesta:"]}'),
	 (174,2,'En su historial de trabajo, ¿ha tenido alguna incapacidad?','single_choice',101,NULL,'Hábitos y salud','Personalizado','Encuesta Médica Leben',NULL),
	 (175,2,'En caso de ser afirmativa la respuesta anterior, mencione de qué tipo','text',102,NULL,'Hábitos y salud','Personalizado','Encuesta Médica Leben','{"otherPrompts": ["Tu Respuesta:"]}'),
	 (176,2,'¿Consume mariguana, heroína, LSD, cocaína barbitúricos, anfetaminas o cualquier otro tipo de drogas psicoactivas?','single_choice',103,NULL,'Hábitos y salud','Personalizado','Encuesta Médica Leben',NULL),
	 (177,2,'Tipo de droga','text',104,NULL,'Hábitos y salud','Personalizado','Encuesta Médica Leben','{"otherPrompts": ["Tu Respuesta:"]}'),
	 (178,2,'Frecuencia','single_choice',105,NULL,'Hábitos y salud','Personalizado','Encuesta Médica Leben',NULL),
	 (179,2,'Selecciona la última ocasión que consumiste','single_choice',106,NULL,'Síntomas y dolor','Personalizado','Encuesta Médica Leben',NULL),
	 (180,2,'¿Ha recibido tratamiento con relación al consumo de drogas psicoactivas?','single_choice',107,NULL,'Síntomas y dolor','Personalizado','Encuesta Médica Leben',NULL);
INSERT INTO question (id,survey_id,`text`,response_type,sort_order,risk_factor,category,guide_type,survey_title,metadata) VALUES
	 (181,2,'¿Pertenece o ha pertenecido a instituciones para su rehabilitación?','single_choice',108,NULL,'Síntomas y dolor','Personalizado','Encuesta Médica Leben',NULL),
	 (182,2,'Las preguntas que a continuación se presentan, se refieren a síntomas que usted puede experimentar en su trabajo, por favor señale cuales son aquellos síntomas que se relacionen con usted y con que frecuencia lo presenta Síntomas oculares','matrix',109,NULL,'Síntomas y dolor','Personalizado','Encuesta Médica Leben','{"rows": ["Sequedad ocular", "Lagrimeo", "Enrojecimiento o comezón ocular", "Dolor ocular", "Hinchazón ocular", "Visión Borrosa"], "columns": ["Muchas veces", "A veces", "Nunca"], "selection": "checkbox"}'),
	 (183,2,'Las preguntas que a continuación se presentan, se refieren a síntomas que usted puede experimentar en su trabajo, por favor señale cuales son aquellos síntomas que se relacionen con usted y con que frecuencia lo presenta Síntomas nasales','matrix',110,NULL,'Síntomas y dolor','Personalizado','Encuesta Médica Leben','{"rows": ["Estornudos frecuentes", "Sequedad nasal", "Congestión nasal", "Rinorrea (goteo o liquido nasal)", "Pérdida del olfato", "Hemorragia nasal"], "columns": ["Muchas veces", "A veces", "Nunca"], "selection": "checkbox"}'),
	 (184,2,'Síntomas de garganta','matrix',111,NULL,'Síntomas y dolor','Personalizado','Encuesta Médica Leben','{"rows": ["Resequedad", "Ronquera", "Irritación", "Dolor de garganta", "Sensación de cuerpo extraño", "Dificultad o dolor al tragar"], "columns": ["Muchas veces", "A veces", "Nunca"], "selection": "checkbox"}'),
	 (185,2,'Síntomas bucales','matrix',112,NULL,'Síntomas y dolor','Personalizado','Encuesta Médica Leben','{"rows": ["Halitosis o mal aliento", "Sequedad bucal", "Sangrado de encías", "Ulceras bucales", "Lesiones o placas blanquecinas"], "columns": ["Muchas veces", "A veces", "Nunca"], "selection": "checkbox"}'),
	 (186,2,'Síntomas cutáneos','matrix',113,NULL,'Síntomas y dolor','Personalizado','Encuesta Médica Leben','{"rows": ["Sequedad en la piel", "Comezón en la piel", "Enrojecimiento", "Ampollas o vesículas", "Ulceras o necrosis"], "columns": ["Muchas veces", "A veces", "Nunca"], "selection": "checkbox"}'),
	 (187,2,'Síntomas digestivos','matrix',114,NULL,'Síntomas y dolor','Personalizado','Encuesta Médica Leben','{"rows": ["Nauseas", "Pérdida del apetito", "Estreñimiento", "Diarrea o vomito", "Dolor abdominal", "Heces o vomito con sangre"], "columns": ["Muchas veces", "A veces", "Nunca"], "selection": "checkbox"}'),
	 (188,2,'Síntomas parecidos a la gripe','matrix',115,NULL,'Síntomas y dolor','Personalizado','Encuesta Médica Leben','{"rows": ["Cansancio o fatiga", "Congestion nasal", "Dolor de cabeza", "Tos", "Fiebre", "Dificultad para respirar"], "columns": ["Muchas veces", "A veces", "Nunca"], "selection": "checkbox"}'),
	 (189,2,'Sistemas dolorosos Indique si tiene molestia o dolor, su frecuencia, si le ha impedido realizar su trabajo actual, y si esa molestia o dolor se han producido coma consecuencia de las tareas que realiza en su puesto de trabajo','matrix',116,NULL,'Síntomas y dolor','Personalizado','Encuesta Médica Leben','{"rows": ["Tiene dolor en esta zona ? Cuello, hombros o espalda alta"], "columns": ["Si", "No", "A veces", "Nunca"], "selection": "checkbox"}'),
	 (190,2,'¿Con qué frecuencia?','single_choice',117,NULL,'Síntomas y dolor','Personalizado','Encuesta Médica Leben',NULL);
INSERT INTO question (id,survey_id,`text`,response_type,sort_order,risk_factor,category,guide_type,survey_title,metadata) VALUES
	 (191,2,'Esta molestia ¿le ha impedido realizar su trabajo?','single_choice',118,NULL,'Síntomas y dolor','Personalizado','Encuesta Médica Leben',NULL),
	 (192,2,'¿Con qué frecuencia?','single_choice',119,NULL,'Síntomas y dolor','Personalizado','Encuesta Médica Leben',NULL),
	 (193,2,'Esta molestia ¿es consecuencia de las tareas del puesto que ocupa?','single_choice',120,NULL,'Síntomas y dolor','Personalizado','Encuesta Médica Leben',NULL),
	 (194,2,'Tiene dolor en alguna de estas zonas abdomen, pecho o espalda baja?','single_choice',121,NULL,'Síntomas y dolor','Personalizado','Encuesta Médica Leben',NULL),
	 (195,2,'¿Con qué frecuencia?','single_choice',122,NULL,'Síntomas y dolor','Personalizado','Encuesta Médica Leben',NULL),
	 (196,2,'Esta molestia ¿le ha impedido realizar su trabajo?','single_choice',123,NULL,'Síntomas y dolor','Personalizado','Encuesta Médica Leben',NULL),
	 (197,2,'¿Con qué frecuencia?','single_choice',124,NULL,'Síntomas y dolor','Personalizado','Encuesta Médica Leben',NULL),
	 (198,2,'Esta molestia ¿es consecuencia de las tareas del puesto que ocupa?','single_choice',125,NULL,'Síntomas y dolor','Personalizado','Encuesta Médica Leben',NULL),
	 (199,2,'Dolor de codos manos y/o muñecas','single_choice',126,NULL,'Síntomas y dolor','Personalizado','Encuesta Médica Leben',NULL),
	 (200,2,'¿Con qué frecuencia?','single_choice',127,NULL,'Síntomas y dolor','Personalizado','Encuesta Médica Leben',NULL);
INSERT INTO question (id,survey_id,`text`,response_type,sort_order,risk_factor,category,guide_type,survey_title,metadata) VALUES
	 (201,2,'Esta molestia ¿le ha impedido realizar su trabajo?','single_choice',128,NULL,'Síntomas y dolor','Personalizado','Encuesta Médica Leben',NULL),
	 (202,2,'¿Con qué frecuencia?','single_choice',129,NULL,'Síntomas y dolor','Personalizado','Encuesta Médica Leben',NULL),
	 (203,2,'Esta molestia ¿es consecuencia de las tareas del puesto que ocupa?','single_choice',130,NULL,'Síntomas y dolor','Personalizado','Encuesta Médica Leben',NULL),
	 (204,2,'Dolor de piernas y pies','single_choice',131,NULL,'Síntomas y dolor','Personalizado','Encuesta Médica Leben',NULL),
	 (205,2,'¿Con qué frecuencia?','single_choice',132,NULL,'Síntomas y dolor','Personalizado','Encuesta Médica Leben',NULL),
	 (206,2,'Esta molestia ¿le ha impedido realizar su trabajo?','single_choice',133,NULL,'Síntomas y dolor','Personalizado','Encuesta Médica Leben',NULL),
	 (207,2,'¿Con qué frecuencia?','single_choice',134,NULL,'Síntomas y dolor','Personalizado','Encuesta Médica Leben',NULL),
	 (208,2,'Esta molestia ¿es consecuencia de las tareas del puesto que ocupa?','single_choice',135,NULL,'Síntomas y dolor','Personalizado','Encuesta Médica Leben',NULL),
	 (209,2,'En su trabajo,  ¿Cuánto tiempo tiene que adoptar o realizar estas posturas? Sentado','single_choice',136,NULL,'Eventos críticos','Personalizado','Encuesta Médica Leben',NULL),
	 (210,2,'De pie','single_choice',137,NULL,'Eventos críticos','Personalizado','Encuesta Médica Leben',NULL);
INSERT INTO question (id,survey_id,`text`,response_type,sort_order,risk_factor,category,guide_type,survey_title,metadata) VALUES
	 (211,2,'Caminando','single_choice',138,NULL,'Eventos críticos','Personalizado','Encuesta Médica Leben',NULL),
	 (212,2,'Caminando mientras subo o bajo niveles diferentes (peldaños, escalera, rampa, etc.)','single_choice',139,NULL,'Eventos críticos','Personalizado','Encuesta Médica Leben',NULL),
	 (213,2,'En postura de rodillas/en cuclillas','single_choice',140,NULL,'Eventos críticos','Personalizado','Encuesta Médica Leben',NULL),
	 (214,2,'Tumbado sobre la espalda o sobre un lado','single_choice',141,NULL,'Eventos críticos','Personalizado','Encuesta Médica Leben',NULL),
	 (215,2,'En su trabajo durante cuanto tiempo tiene que adoptar o realizar estas posturas de cuello/cabeza y ¿con que frecuencia? Inclinar el cuello/ cabeza a hacia delante.','single_choice',142,NULL,'Eventos críticos','Personalizado','Encuesta Médica Leben',NULL),
	 (216,2,'Inclinar el cuello/cabeza','single_choice',143,NULL,'Eventos críticos','Personalizado','Encuesta Médica Leben',NULL),
	 (217,2,'Inclinar el cuello/cabeza hacia un lado o ambos','single_choice',144,NULL,'Eventos críticos','Personalizado','Encuesta Médica Leben',NULL),
	 (218,2,'En su trabajo, durante cuanto tiempo tiene que adoptar o realizar estas posturas de espalda/tronco y ¿con que frecuencia? Inclinar la espalda/tronco hacia delante','single_choice',145,NULL,'Eventos críticos','Personalizado','Encuesta Médica Leben',NULL),
	 (219,2,'Inclinar la espalda/tronco hacia atrás','single_choice',146,NULL,'Eventos críticos','Personalizado','Encuesta Médica Leben',NULL),
	 (220,2,'Inclinar la espalda/tronco hacia un lado o ambos','single_choice',147,NULL,'Eventos críticos','Personalizado','Encuesta Médica Leben','{"otherOption": true, "otherPrompts": ["Otros:"]}');
INSERT INTO question (id,survey_id,`text`,response_type,sort_order,risk_factor,category,guide_type,survey_title,metadata) VALUES
	 (221,2,'Girar la espalda/tronco','single_choice',148,NULL,'Eventos críticos','Personalizado','Encuesta Médica Leben',NULL),
	 (222,2,'En su trabajo, durante cuanto tiempo tiene que adoptar o realizar estas posturas de hombros, muñecas y tobillos/pies, y ¿con que frecuencia? Las manos por encima de la cabeza o los codos por encima de los hombros','single_choice',149,NULL,'Eventos críticos','Personalizado','Encuesta Médica Leben',NULL),
	 (223,2,'Ejerciendo presión con uno de los pies','single_choice',150,NULL,'Eventos críticos','Personalizado','Encuesta Médica Leben',NULL),
	 (224,2,'En su trabajo, durante ¿Cuánto tiempo tiene que adoptar o realizar estas acciones con las manos? Sostener, presionar o levantar objetos o herramientas con los dedos en forma de pinza','single_choice',151,NULL,'Eventos críticos','Personalizado','Encuesta Médica Leben',NULL),
	 (225,2,'Agarrar o sujetar con fuerza objetos o herramientas con las manos','single_choice',152,NULL,'Eventos críticos','Personalizado','Encuesta Médica Leben',NULL),
	 (226,2,'Utilizar de manera intensiva los dedos, (ordenador, controles, botoneras, mando, calculadora, caja registradora, etc.)','single_choice',153,NULL,'Eventos críticos','Personalizado','Encuesta Médica Leben',NULL),
	 (227,2,'En su trabajo, ¿durante cuanto tiempo tiene que trabajar realizando estas acciones relacionadas con la exposición a vibraciones y/o impactos?','single_choice',154,NULL,'Eventos críticos','Personalizado','Encuesta Médica Leben',NULL),
	 (228,2,'Trabajar sobre superficies vibrantes (asiento de vehículo, plataforma o suelo vibrante, etc.)','single_choice',155,NULL,'Eventos críticos','Personalizado','Encuesta Médica Leben',NULL),
	 (229,2,'Utilizar herramientas y máquinas de impacto o vibrantes (taladro, remachadora, amoladora, martillo, grapadora neumática, etc.)','single_choice',156,NULL,'Eventos críticos','Personalizado','Encuesta Médica Leben',NULL),
	 (230,2,'Utilizar la mano (el pie o la rodilla) como martillo, golpeando de forma repetida','single_choice',157,NULL,'Eventos críticos','Personalizado','Encuesta Médica Leben',NULL);
INSERT INTO question (id,survey_id,`text`,response_type,sort_order,risk_factor,category,guide_type,survey_title,metadata) VALUES
	 (231,2,'Levantar Manualmente , objetos, herramientas, materiales de mas de  3kg. ¿Durante cuanto tiempo tienes que trabajar realizando esta acción?','single_choice',158,NULL,'Eventos críticos','Personalizado','Encuesta Médica Leben',NULL),
	 (232,2,'Los pesos que con mayor frecuencia levantas son de','single_choice',159,NULL,'Eventos críticos','Personalizado','Encuesta Médica Leben',NULL),
	 (233,2,'Señala si habitualmente','single_choice',160,NULL,'Eventos críticos','Personalizado','Encuesta Médica Leben',NULL),
	 (234,2,'Transportar manualmente objetos, herramientas, materiales de mas de 3kg. ¿Durante cuanto tiempo tienes que trabajar realizando esta acción?','single_choice',161,NULL,'Eventos críticos','Personalizado','Encuesta Médica Leben',NULL),
	 (235,2,'Los pesos que con mayor frecuencia levantas son de','single_choice',162,NULL,'Eventos críticos','Personalizado','Encuesta Médica Leben',NULL),
	 (236,2,'Señala si habitualmente','single_choice',163,NULL,'Eventos críticos','Personalizado','Encuesta Médica Leben',NULL),
	 (237,2,'Empujar y/o arrastrar manualmente utilizando algún equipo (carretilla, transpaleta, carro...) objetos, herramientas, materiales de mas de 3kg. ¿Durante cuanto tiempo tienes que trabajar realizando esta acción?','single_choice',164,NULL,'Eventos críticos','Personalizado','Encuesta Médica Leben',NULL),
	 (238,2,'Señala si habitualmente','single_choice',165,NULL,'Eventos críticos','Personalizado','Encuesta Médica Leben',NULL),
	 (239,2,'Accidente que tenga como consecuencia la muerte, la pérdida de un miembro o una lesión grave','single_choice',166,NULL,'Eventos críticos','Personalizado','Encuesta Médica Leben',NULL),
	 (240,2,'Actos violentos que derivaron de lesiones graves','single_choice',167,NULL,'Eventos críticos','Personalizado','Encuesta Médica Leben',NULL);
INSERT INTO question (id,survey_id,`text`,response_type,sort_order,risk_factor,category,guide_type,survey_title,metadata) VALUES
	 (241,2,'Asaltos','single_choice',168,NULL,'Eventos críticos','Personalizado','Encuesta Médica Leben',NULL),
	 (242,2,'Secuestros','single_choice',169,NULL,'Eventos críticos','Personalizado','Encuesta Médica Leben',NULL),
	 (243,2,'Si usted ha contestado que ''SI'' a una o más de las preguntas anteriores, favor de contestar las siguientes:
¿Durante el último mes?','single_choice',170,NULL,'Eventos críticos','Personalizado','Encuesta Médica Leben',NULL),
	 (244,2,'¿Ha tenido recuerdos recurrentes sobre el acontecimiento que le provocan malestares?','single_choice',171,NULL,'Eventos críticos','Personalizado','Encuesta Médica Leben',NULL),
	 (245,2,'¿Ha tenido sueños de carácter recurrente sobre el acontecimiento, que le producen malestar?','single_choice',172,NULL,'Eventos críticos','Personalizado','Encuesta Médica Leben',NULL),
	 (246,2,'Durante el último mes ¿Se ha esforzado para evitar todo tipo de sentimientos, conversaciones o situaciones que le puedan recordar el acontecimiento?','single_choice',173,NULL,'Eventos críticos','Personalizado','Encuesta Médica Leben',NULL),
	 (247,2,'¿Se ha esforzado para evitar todo tipo de actividades, lugares o personas que motivan recuerdos del acontecimiento?','single_choice',174,NULL,'Eventos críticos','Personalizado','Encuesta Médica Leben',NULL),
	 (248,2,'¿Ha tenido dificultad para recordar alguna parte importante del evento?','single_choice',175,NULL,'Eventos críticos','Personalizado','Encuesta Médica Leben',NULL),
	 (249,2,'¿Ha disminuido su interés en sus actividades cotidianas?','single_choice',176,NULL,'Eventos críticos','Personalizado','Encuesta Médica Leben',NULL),
	 (250,2,'¿Se ha sentido usted alejado o distante de las demás?','single_choice',177,NULL,'Eventos críticos','Personalizado','Encuesta Médica Leben',NULL);
INSERT INTO question (id,survey_id,`text`,response_type,sort_order,risk_factor,category,guide_type,survey_title,metadata) VALUES
	 (251,2,'¿Ha notado que tiene dificultad para expresar sus sentimientos?','single_choice',178,NULL,'Eventos críticos','Personalizado','Encuesta Médica Leben',NULL),
	 (252,2,'Ha tenido la impresión de que su vida se va a acortar, ¿Qué va a morir antes que otras personas o que tiene un futuro limitado?','single_choice',179,NULL,'Eventos críticos','Personalizado','Encuesta Médica Leben',NULL),
	 (253,2,'¿Ha estado particularmente irritable o le han dado arranques de coraje?','single_choice',180,NULL,'Eventos críticos','Personalizado','Encuesta Médica Leben',NULL),
	 (254,2,'¿Ha tenido dificultad para concentrarse?','single_choice',181,NULL,'Eventos críticos','Personalizado','Encuesta Médica Leben',NULL),
	 (255,2,'¿Ha estado nervioso o constantemente en alerta?','single_choice',182,NULL,'Eventos críticos','Personalizado','Encuesta Médica Leben',NULL),
	 (256,2,'¿Se ha sobresaltado fácilmente para cualquier cosa?','single_choice',183,NULL,'Eventos críticos','Personalizado','Encuesta Médica Leben',NULL);